-- PROCEDURE DU NO QUA HAN 
CREATE TABLE INC_DNQH
(
	MONTH_ID VARCHAR2(30)
	, LOAN_CODE VARCHAR2(30)
	, SHOP_CODE NUMBER(38,0)
	, PRINCIPAL_REMAIN NUMBER(38,0)
	, EMPLOYEE_CODE VARCHAR2(30)
	, CREATED_DT VARCHAR2(30)
	, SCHEDULE_NEXT_DATE VARCHAR2(30)
); 

----- 
CREATE OR REPLACE PROCEDURE INSERT_INC_DNQH_CVKD(P_DATE IN DATE)
AS 
	YEAR_MONTH_ID NUMBER; 
	YEAR_MONTH_DAY NUMBER;
BEGIN 
	YEAR_MONTH_ID := TO_CHAR(P_DATE, 'YYYYMM');
	YEAR_MONTH_DAY := TO_NUMBER(TO_CHAR(P_DATE, 'YYYYMMDD')); 

DELETE 
FROM BACHPX.INC_DNQH 
WHERE 
	1=1
	AND MONTH_ID = YEAR_MONTH_ID 
; 

INSERT INTO INC_DNQH 
	SELECT
	YEAR_MONTH_ID AS MONTH_ID
	, LD.LOAN_CODE 
	, S.SHOP_CODE
	, LD1.PRINCIPAL_REMAIN AS DU_NO_QUA_HAN 
	, F.EMPLOYEE_CODE AS SUPPORTER_CODE
	, LDT.CREATED_DT
	, LD.SCHEDULE_NEXT_DATE 
FROM F88DWH.W_LOAN_DAILY_F LD

--LEFT JOIN (SELECT DISTINCT LOAN_WID, SHOP_WID, CHANNEL_WID 
--				FROM F88DWH.W_LOAN_OFFICE_F) LOF ON LD.LOAN_WID = LOF.LOAN_WID 
	LEFT JOIN F88DWH.W_SHOP_D S ON LD.SHOP_WID = S.SHOP_WID 
--	LEFT JOIN F88DWH.W_CHANNEL_D CD ON LOF.CHANNEL_WID = CD.CHANNEL_WID 
	LEFT JOIN F88DWH.W_ASSET_TP_D ATP ON LD.ASSET_TYPE_WID = ATP.ASSET_TP_WID 
	LEFT JOIN 
	F88DWH.W_LOAN_DAILY_F LD1 ON LD.LOAN_WID = LD1.LOAN_WID 
							  AND LD.SCHEDULE_NEXT_DATE = TO_DATE(LD1.DATE_WID, 'YYYY MM DD')
	LEFT JOIN F88DWH.W_LOAN_DTL_F LDT ON LD.LOAN_WID = LDT.LOAN_WID 
	LEFT JOIN F88DWH.W_EMPLOYEE_D F ON LD1.SUPPORTER_WID = F.EMPLOYEE_WID 
	
WHERE 
	1=1 
	AND ATP.ASSET_TP_CODE IN ('00000015', '00000017')
	AND LD.OVERDUE_DAYS = -1 
	AND LD.STATUS <> 603
	AND LD1.YEAR_NUM = SUBSTR(YEAR_MONTH_ID, 1, 4)
	AND LD1.MONTH_NUM = SUBSTR(YEAR_MONTH_ID, 5, 2) 
	AND LD1.OVERDUE_DAYS_ADJUST = 1
	AND LDT.CHANNEL_CODE = 'KDML'
	AND UPPER(S.SHOP_NM)  NOT LIKE '%TELESALE%'
	AND LD.LOAN_CODE NOT IN (SELECT B.LOAN_CODE FROM BACHPX.INCENTIVE_DELETE_LOAN_CODE B WHERE LOAI='DU NO QUA HAN' AND MONTH_ID='202212')

ORDER BY S.SHOP_CODE ASC 
; 
DBMS_OUTPUT.PUT_LINE('INSERT COMPLETELY!'); 
END; 

BEGIN 
	INSERT_INC_DNQH_CVKD('31-DEC-2022');
END;

